### ISSUE TITLE
Anicent Fruit Buy Price should be $0?

### ISSUE THREAD

**Issue by Em31Et** [exnil/crop_planner#2]
Since there are no shop selling Anicent Seed.

**Comment by exnil** [comment]
While they can be acquired through other technically free means, they can also be purchased from the Traveling Cart for 900g. In calculating profit and costs it is best to consider the worst case scenario, which is, in this case, spending 900g.

**Comment by forlornhedgehog** [comment]
What's your source for 900g Ancient Seeds price? [Wiki](http://stardewvalleywiki.com/Travelling_Cart) and an [Arqade answer](http://gaming.stackexchange.com/a/259042) cite 400-700g.

**Comment by exnil** [comment]
It must have fluctuated a bit since I last updated the values (several months ago), but I got its current price (800g) from an earlier revision of the Crops page on the wiki. I'll update its price, thanks.
