### ISSUE TITLE
Per season limited crops not working on Safari

### ISSUE THREAD

**Issue by jfgoncalves** [exnil/crop_planner#5]
Eg: On Summer, click on a day. Now choose a crop in the dropdown list. On Chrome, only the crops for Summer are available (normal behavior). On Safari (OS X and iOS) all the crops are available in the dropdown list.

**Comment by exnil** [comment]
Thanks. This should be fixed now, though I don't have Safari to test it. Would you be able to check and let me know if it's working now?

**Comment by jfgoncalves** [comment]
Yep it's fixed now, on both platforms.
