### ISSUE TITLE
App doesn't work over HTTPS

### ISSUE THREAD

**Issue by jfgoncalves** [exnil/crop_planner#7]
Simple fix would be to serve the HTTPS version of angular.

Mixed Content: The page at 'https://exnil.github.io/crop_planner/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by exnil** [comment]
Thanks, this has been fixed.
Must have slipped in when I copy/pasted a newer version of the Angular script.
